# Setup
title:               martin19's blog
tagline:             'development notes of martin19'
description:         'this blog is literally a web logfile of my thoughts in progress, posting about digital things i care about.'
url:                 https://martin19.github.io
baseurl:             /
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              martin19 on github
  url:               https://twitter.com/@wearecloudpaint
  email:             contact@cloudpaint.com

# Gems
plugins:
  - jekyll-paginate

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge  

# Custom vars
#version:             1.1.0
#google_analytics_id: #UA-XXXX-Y
